import React, { useState } from 'react';
import { ArrowLeft, CheckCircle2, IndianRupee, Search, ShieldCheck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const schemes = [
  { name: 'PM-KISAN', type: 'Farmer', income: 2500000, benefit: '₹6,000 yearly income support for eligible farmer families.' },
  { name: 'Ayushman Bharat (PM-JAY)', type: 'any', income: Infinity, benefit: 'Check your family’s eligibility for health assurance.' },
  { name: 'PM Awas Yojana – Urban', type: 'any', income: 600000, benefit: 'Housing support for eligible urban households.' },
  { name: 'Pradhan Mantri MUDRA Yojana', type: 'Business owner', income: Infinity, benefit: 'Collateral-free business loans for eligible micro enterprises.' },
  { name: 'Post-Matric Scholarship for SC Students', type: 'Student', income: 250000, benefit: 'Fee and maintenance support for eligible SC students.' },
];

export default function SchemeEligibilityPage() {
  const navigate = useNavigate();
  const [profile, setProfile] = useState({ age: '', occupation: '', income: '' });
  const [checked, setChecked] = useState(false);
  const results = schemes.filter((scheme) => (scheme.type === 'any' || scheme.type === profile.occupation) && (Number(profile.income || 0) <= scheme.income));
  return <div className="tracker-page"><div className="app-background-pattern" /><header className="tracker-topbar"><button type="button" onClick={() => navigate('/dashboard')}><ArrowLeft size={18} /> Dashboard</button><div className="tracker-brand"><ShieldCheck size={22} /><span>SevaAI</span><em>Scheme Eligibility</em></div><span /></header><main className="tracker-main"><section className="tracker-hero"><div><p>SCHEMES FOR YOU</p><h1>Find scheme eligibility</h1><span>Answer a few questions to see preliminary matches. Final eligibility is decided by the official scheme portal.</span></div><Search size={55} /></section><section className="tracker-records-section" style={{ marginTop: '1.5rem', maxWidth: 760 }}><h2>Tell us about yourself</h2><p style={{ color: 'var(--color-text-muted)', marginTop: '.25rem' }}>Your details stay in this browser for this check.</p><div className="quick-filters" style={{ marginTop: '1.25rem' }}><input aria-label="Age" type="number" min="0" max="120" value={profile.age} onChange={(e) => setProfile({ ...profile, age: e.target.value })} placeholder="Your age" /><select aria-label="Occupation" value={profile.occupation} onChange={(e) => setProfile({ ...profile, occupation: e.target.value })}><option value="">Select occupation</option><option>Farmer</option><option>Student</option><option>Business owner</option><option>Employee</option><option>Other</option></select><input aria-label="Annual family income" type="number" min="0" value={profile.income} onChange={(e) => setProfile({ ...profile, income: e.target.value })} placeholder="Annual family income (₹)" /></div><button type="button" className="btn btn-primary" onClick={() => setChecked(true)} disabled={!profile.age || !profile.occupation}> <Search size={17} /> Check eligibility</button>{checked && <div style={{ marginTop: '1.5rem' }}><h3>Preliminary matches</h3>{results.length ? results.map((scheme) => <article className="tracker-summary-card" style={{ marginTop: '.75rem' }} key={scheme.name}><span className="tracker-summary-icon green"><CheckCircle2 size={20} /></span><div><strong style={{ fontSize: '1rem' }}>{scheme.name}</strong><p>{scheme.benefit}</p></div></article>) : <p style={{ marginTop: '.75rem', color: 'var(--color-text-muted)' }}>No preliminary matches found. Try updating your details or browse official government scheme portals.</p>}<p style={{ marginTop: '1rem', fontSize: '.8rem', color: 'var(--color-text-muted)' }}><IndianRupee size={13} /> This is a preliminary guide adapted from the Scheme Eligibility feature. Verify all criteria and apply only through official portals.</p></div>}</section></main></div>;
}
